---
language: generic

matrix:
  include:
    - os: linux
      env: PYTHON=3.6
    - os: osx
      env: PYTHON=3.6

env:
  global:
    - PACKAGE_NAME=whitenoise
    - ANACONDA_USER="${TRAVIS_REPO_SLUG%/*}"
    - PATH="$HOME/miniconda/bin:$PATH"

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
        wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda && rm miniconda.sh
  - conda install -y conda-build anaconda-client
  - conda info -a

script:
  - conda build --python $PYTHON .

deploy:
  - provider: script
    skip_cleanup: true
    script: anaconda -t $CONDA_UPLOAD_TOKEN upload --user $ANACONDA_USER $HOME/miniconda/conda-bld/noarch/$PACKAGE_NAME-*.tar.bz2
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
